### PR TITLE
Initlal major `develop` to `main` branch merge

### PR DESCRIPTION
**Pull request by anilnatha**
## 🗒️ Summary

This PR addresses the need to cut a release that includes changes for our first major release of the PDS Web Modernization Effort website.

This includes, but not limited to:

* Creation of website framework that includes our code infrastructure, integration of `wds-react` and redux, component development, layout and routing integration.
* Development of key pages of our MVP:
    * Homepage
    * Search
    * Investigations Directory Page
    * Investigations Detail Page
    * Instruments Directory Page
    * Instruments Detail Page 
* Components for MVP
    * Header (includes titlebar and navbar)
    * Footer
    * Cards
    * Explore Modules (4-up and 6-up)
    * Search Filters
    * Investigation Status
    * StatsList and StatsItem for detail pages
    * DocumentMeta (to inject page metadata)
* Enhancements to Vite tooling include:
    * Updated configuration to support `wds-react` integration and code preview
    * Integration of roundup actions including secrets detection

## ⚙️ Test Data and/or Report

Code has been tested using builds of the `develop` branch.

### CODE REVIEW

**Comment by anilnatha** [comment]
@eddiesarevalo If there is anything I accidentally forgot to include in the PR notes, please let me know.

**Comment by eddiesarevalo** [comment]
@anilnatha some other items that we can add to the PR notes are: Components that are not complete pages but important include the navbar, footer and loading screen. We should also mention the workflow updates in Vite and CI/CD.

We should update the version number from 0.0.0

**Comment by anilnatha** [comment]
@eddiesarevalo I'll update the PR notes later this afternoon. Thank you! Let me know if you think of anything else.

**Review by eddiesarevalo — APPROVED** [review]
This is ready for main! Approved!

**Pull request merged**
