### PR TITLE
Update sorting of collection information

### LINKED ISSUE #86: Add sorting of Collections
### 💡 Description

We received feedback that it isn't obvious to users what the sort order is of collections on the instrument's detail page.

Tasks
- [x] Sort the Processing Level groups by following the logical data pipeline order (i.e. raw -> partially processed -> calibrated)
- [x] Sort collections associated with a processing level in ascending (A-Z) order.

### ⚔️ Parent Epic / Related Tickets

_No response_

### LINKED ISSUE #89: "Unknown Processing Level" isn't shown when a collection's processing level is "null"
### 💡 Description

As the title states, the API returns the string `"null"` when a collection has no processing level. When this happens, it's processing level title should be labeled as "Unknown Processing Level", but instead it's blank.

Example of the issue for [Mars Global Surveyor](https://pds.mcp.nasa.gov/portal/investigations/urn--nasa--pds--context--investigation--mission---mars----global----surveyor/instruments):

image

### ⚔️ Parent Epic / Related Tickets

_No response_

### PR DESCRIPTION
**Pull request by anilnatha**
## 🗒️ Summary

This PR addresses the following:

* Instrument Detail Page: Processing levels and their related collections listed on the Data Tab are now sorted
* Investigation Detail Page
    * Processing levels and their related collections listed in expanded area of Instruments on the Instruments Tab are now sorted
    * Fixes a bug when collections have no processing level, and they aren't labeled as "Unknown Processing Level"

## ⚙️ Test Data and/or Report

Tested locally and ensured that `npm run build` does not generate errors.

## ♻️ Related Issues

Fixes #86 
Fixes #89

### CODE REVIEW

**Comment by anilnatha** [comment]
@nutjob4life I had to run the secrets baseline and audit again for this PR because the code scans failed. Can you please verify I did that correctly.

**Review by nutjob4life — APPROVED** [review]
LGTM

**Comment by anilnatha** [comment]
@eddiesarevalo @nutjob4life I made some substantial changes to improve rendering performance and resolve a bug I found on our production site that I thought I would fix as part of this PR.

**Comment by anilnatha** [comment]
@eddiesarevalo The changes in this PR are now reliant on a wds-react PR: https://github.com/NASA-PDS/wds-react/pull/72

**Review by nutjob4life — APPROVED** [review]
This approval is just for the secrets baseline; I'll let @eddiesarevalo who is better at React to weigh in on the rest 👍

**Review by eddiesarevalo — APPROVED** [review]
Tested and worked well. Build runs as well.

**Pull request merged**
