### PR TITLE
Updated Vite Proxy

### LINKED ISSUE #11: Update Vite server config for local registry proxy
### 💡 Description

Our Vite config was previously proxying to pds.nasa.gov to work around CORS issues, but with our API currently not available, we need to run an instance of the registry locally so the proxy needs to be updated.

### ⚔️ Parent Epic / Related Tickets

_No response_

### PR DESCRIPTION
**Pull request by anilnatha**
## 🗒️ Summary

The Vite proxy has been updated so that requests for information from the API are fetched from a locally running instance of the registry.  An accept header was also added to all data requests to resolve an error being reported by the API about invalid data type being requested.

Note: this only affects local development.

## ⚙️ Test Data and/or Report

Verified dev proxy configuration is working by running the dev server locally and ensuring that data could be retrieved from the locally running instance of the registry.

## ♻️ Related Issues

Fixes #11

### CODE REVIEW

**Comment by anilnatha** [comment]
@nutjob4life Yea, let's chat. If there is time during the breakout, let's tackle this or we can speak tomorrow (the 16th).

I had taken a look at the generated `.secrets.baseline` files, which is what prompted my concern that it doesn't contain everything that it should.

**Comment by anilnatha** [comment]
@nutjob4life I updated the secrets.baseline file once more.  Something with the last command I ran was funky which is why it hadn't picked up on the emails in the dockerfiles and other files. That should be fixed now.

Also, I've added the two secrets detection commands to the project's Makefile which will help.

Last question, does the secrets detection command in `.github/workflows/secrets-detection.yml` need to be updated since this is a Node.js repo?

**Comment by nutjob4life** [comment]
@anilnatha great to hear! Glad it's working better

Checking the `.github/workflows/secrets-detection.yaml` file … yeah, it'll need to updated too. Just remove all the Python stuff and add `--exclude-files node_modules`

**Comment by anilnatha** [comment]
@nutjob4life the `.github/workflows/secrets-detection.yaml` has been updated.

**Review by nutjob4life — APPROVED** [review]

**Comment by nutjob4life** [comment]
@anilnatha 🎉

**Pull request merged**
